realm: acme
enabled: true
displayName: ACME
resetPasswordAllowed: true

components:
  org.keycloak.storage.UserStorageProvider:
    - name: ACME LDAP
      providerId: ldap
      subComponents:
        org.keycloak.storage.ldap.mappers.LDAPStorageMapper:
          - name: "first name"
            providerId: user-attribute-ldap-mapper
            subComponents: {}
            config:
              ldap.attribute: ["givenName"]
              user.model.attribute: ["firstName"]
#          - name: "LDAP Group Mapper"
#            providerId: group-ldap-mapper
#            subComponents: {}
#            config:
#              membership.attribute.type: ["DN"]
#              group.name.ldap.attribute: ["cn"]
#              preserve.group.inheritance: ["false"]
#              membership.user.ldap.attribute: ["uid"]
#              groups.dn: ["$(env:LDAP_GROUP_DN:-dc=corp,dc=acme,dc=local)"]
#              mode: ["READ_ONLY"]
#              user.roles.retrieve.strategy: ["LOAD_GROUPS_BY_MEMBER_ATTRIBUTE"]
#              ignore.missing.groups: ["true"]
#              membership.ldap.attribute: ["member"]
#              group.object.classes: ["groupOfNames"]
#              memberof.ldap.attribute: ["memberOf"]
#              groups.path: ["/"]
#              drop.non.existing.groups.during.sync: ["false"]
          - name: "Confluence Group Mapper"
            providerId: confluence-group-ldap-mapper
            subComponents: {}
            config:
              confluenceContent.baseUrl: ["$(env:CONFLUENCE_URL:-confluence-url)"]
              confluenceContent.authToken: ["token"]
              confluenceContent.parentPageId: [ "1234"]
              confluenceContent.pageNesting: ["4"]
              confluenceContent.spaceKey: ["TEST"]
              confluenceContent.pageLabels: ["label1, label2, label3"]
              confluenceContent.pagePropertyName: ["Members"]
              confluenceContent.memberColumnIndex: ["1"]
              confluenceGroups.dropNonExistingGroups: ["true"]
              confluenceGroups.groupsPath: ["/"]
      config:
        enabled: ["true"]
        pagination: ["true"]
        fullSyncPeriod: ["-1"]
        searchScope: ["2"]
        useTruststoreSpi: ["ldapsOnly"]
        usersDn: ["$(env:LDAP_USERS_DN:-dc=corp,dc=acme,dc=local)"]
        maxLifespan: ["3600000"]
        connectionPooling: ["true"]
        cachePolicy: ["NO_CACHE"]
        priority: ["0"]
        importEnabled: ["true"]
        useKerberosForPasswordAuthentication: ["false"]
        usePasswordModifyExtendedOp: ["true"]
        trustEmail: ["false"]
        userObjectClasses: ["inetOrgPerson, organizationalPerson"]
        bindDn: ["$(env:LDAP_USER:-ldap_user)"]
        usernameLDAPAttribute: ["uid"]
        changedSyncPeriod: ["-1"]
        bindCredential: ["$(env:LDAP_PASSWORD:-ldap_password)"]
        rdnLDAPAttribute: ["uid"]
        vendor: ["other"]
        editMode: ["READ_ONLY"]
        uuidLDAPAttribute: ["entryUUID"]
        connectionUrl: ["$(env:LDAP_URL:-ldap://localhost:389)"]
        syncRegistrations: ["false"]
        authType: ["simple"]
        batchSizeForSync: ["1000"]
        changedSyncEnabled: ["false"]
        validatePasswordPolicy: ["false"]
